eureka:
  instance:
#    prefer-ip-address: true
    hostname: service-registry
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://service-registry:8761/eureka}
